"use client";
import { useEffect, useState } from "react";
import { Loader2, ShieldCheck } from "lucide-react";
import { useRouter } from "next/navigation";
import { useAuth } from "@/hooks/useAuth";
import { useActivePersonId } from "@/hooks/useActivePersonId";
import { personsRepository } from "@/lib/repositories/persons";
import { db } from "@/lib/db";
export default function OnboardingPage(){const router=useRouter();const {user,loading}=useAuth();const {changePerson}=useActivePersonId();const [name,setName]=useState("");const [email,setEmail]=useState("");const [avatar,setAvatar]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");useEffect(()=>{if(loading)return;if(!user){router.replace("/login");return}const meta=user.user_metadata||{};setName(String(meta.full_name||meta.name||"").trim());setEmail(user.email||"");setAvatar(String(meta.avatar_url||meta.picture||"").trim());void db.persons.where("user_id").equals(user.id).count().then(c=>{if(c>0)router.replace("/")})},[user,loading,router]);async function confirm(){if(!name.trim())return;setBusy(true);setError("");try{const existing=await db.persons.where("user_id").equals(user!.id).first();const p=existing||await personsRepository.create({name,email,avatar_url:avatar});await changePerson(p.id!);router.replace("/")}catch(e){setError(e instanceof Error?e.message:"Não foi possível criar o perfil.")}finally{setBusy(false)}}return <main className="flex min-h-screen items-center justify-center bg-void p-5 text-ink-primary"><section className="w-full max-w-md rounded-[28px] border border-surface-border bg-surface p-6"><ShieldCheck className="mb-4 text-ice" size={34}/><h1 className="font-display text-2xl font-bold">Sua pessoa principal</h1><p className="mt-2 text-sm text-ink-muted">Confira antes de criar. Primeiro buscamos seus dados sincronizados para evitar perfil duplicado.</p>{avatar&&<img src={avatar} alt="Foto do perfil" className="mt-5 h-16 w-16 rounded-2xl object-cover"/>}<label className="mt-5 block text-xs text-ink-muted">Nome</label><input value={name} onChange={e=>setName(e.target.value)} className="mt-1 w-full rounded-xl border border-surface-border bg-void p-3"/><label className="mt-4 block text-xs text-ink-muted">E-mail</label><input value={email} onChange={e=>setEmail(e.target.value)} className="mt-1 w-full rounded-xl border border-surface-border bg-void p-3"/>{error&&<p className="mt-3 text-sm text-coral">{error}</p>}<button disabled={busy||!name.trim()} onClick={confirm} className="mt-6 flex w-full items-center justify-center rounded-xl bg-ice p-3 font-semibold text-void">{busy?<Loader2 className="animate-spin"/>:"Confirmar e entrar"}</button></section></main>}
