"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Activity, ArrowLeft, CalendarDays, FileDown, HeartPulse, Info, Pill, Printer, Stethoscope } from "lucide-react";
import { PageTransition } from "@/components/PageTransition";
import { CardListSkeleton } from "@/components/loading/CardListSkeleton";
import { EmptyState } from "@/components/EmptyState";
import { useHealthIntelligence } from "@/hooks/useHealthIntelligence";
import { buildClinicalReport, type ClinicalReportPeriod } from "@/lib/clinical-report";

const periods: ClinicalReportPeriod[] = [7, 30, 90];
const displayDate = (value: string) => { const [year, month, day] = value.split("-"); return `${day}/${month}/${year}`; };
const deltaLabel = (value: number | null) => value === null ? "Novo no período" : value === 0 ? "Estável" : `${value > 0 ? "+" : ""}${value}%`;

export default function ClinicalReportPage() {
  const router = useRouter();
  const intelligence = useHealthIntelligence();
  const [period, setPeriod] = useState<ClinicalReportPeriod>(30);
  const report = useMemo(() => intelligence.context ? buildClinicalReport(intelligence.context, intelligence.insights, period) : null, [intelligence.context, intelligence.insights, period]);

  if (intelligence.isLoading) return <CardListSkeleton />;
  if (!intelligence.hasPerson || !intelligence.context) return <EmptyState icon={Stethoscope} title="Pessoa não selecionada" description="Selecione uma pessoa para gerar o relatório clínico." />;
  if (!report) return null;

  return <PageTransition><main className="min-h-screen bg-void pb-28 print:bg-white print:pb-0 print:text-black">
    <header className="sticky top-0 z-20 border-b border-surface-border/40 bg-void/90 px-5 pb-4 pt-safe backdrop-blur-xl print:static print:border-gray-300 print:bg-white">
      <div className="flex items-center gap-3"><button type="button" onClick={() => router.replace("/saude/registros")} className="flex h-11 w-11 items-center justify-center rounded-full border border-surface-border bg-surface-raised print:hidden" aria-label="Voltar ao prontuário"><ArrowLeft size={18}/></button><div className="min-w-0 flex-1"><p className="font-mono text-[9px] uppercase tracking-[0.24em] text-emerald-300 print:text-gray-700">Prontuário clínico</p><h1 className="font-display text-xl font-semibold text-ink-primary print:text-black">Relatório do período</h1><p className="text-[10px] text-ink-muted print:text-gray-600">Síntese descritiva e explicável</p></div><button type="button" onClick={() => window.print()} className="flex h-11 w-11 items-center justify-center rounded-2xl bg-emerald-300 text-void print:hidden" aria-label="Imprimir ou salvar PDF"><Printer size={19}/></button></div>
      <div className="mt-4 grid grid-cols-3 gap-2 print:hidden">{periods.map((days) => <button key={days} type="button" onClick={() => setPeriod(days)} className={`rounded-xl border py-2 text-xs font-semibold ${period === days ? "border-emerald-300 bg-emerald-300/10 text-emerald-300" : "border-surface-border bg-surface-raised text-ink-muted"}`}>{days} dias</button>)}</div>
    </header>
    <section className="space-y-4 px-5 pt-4 print:px-0">
      <div className="rounded-[26px] border border-emerald-300/20 bg-gradient-to-br from-emerald-300/[0.09] to-surface p-4 print:border-gray-300 print:bg-white"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-widest text-emerald-300 print:text-gray-700">Período analisado</p><h2 className="mt-1 text-lg font-semibold text-ink-primary print:text-black">{displayDate(report.current.start)} a {displayDate(report.current.end)}</h2><p className="mt-1 text-[11px] text-ink-muted print:text-gray-600">{report.coverage.currentDays} de {period} dias possuem dados. Ausência de registro não é interpretada como zero.</p></div><FileDown size={22} className="text-emerald-300"/></div></div>

      <section className="rounded-[24px] border border-surface-border bg-surface p-4 print:border-gray-300 print:bg-white"><SectionTitle icon={Activity} title="Visão geral"/><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4"><Metric label="Registros clínicos" value={report.totals.records}/><Metric label="Sintomas" value={report.totals.symptoms}/><Metric label="Doses programadas tomadas" value={report.totals.scheduledTaken}/><Metric label="SOS / extras tomadas" value={report.totals.sosTaken + report.totals.extraTaken}/><Metric label="Medições" value={report.totals.measurements}/><Metric label="Hidratação" value={report.totals.hydrationRecords}/><Metric label="Doses ignoradas" value={report.totals.ignored}/><Metric label="Tratamentos ativos" value={report.activeTreatments.length}/></div></section>

      <section className="rounded-[24px] border border-surface-border bg-surface p-4 print:border-gray-300 print:bg-white"><SectionTitle icon={CalendarDays} title="Comparação equivalente"/><p className="mt-1 text-[10px] text-ink-muted print:text-gray-600">Comparação com {displayDate(report.previous.start)} a {displayDate(report.previous.end)}. Variação reflete registros disponíveis, não mudança clínica confirmada.</p><div className="mt-3 grid grid-cols-3 gap-2"><Comparison label="Registros" value={report.comparison.recordsDelta}/><Comparison label="Sintomas" value={report.comparison.symptomDelta}/><Comparison label="SOS/extra" value={report.comparison.sosExtraDelta}/></div><p className="mt-3 text-[9px] text-ink-faint print:text-gray-600">Cobertura: {report.coverage.currentDays}/{period} dias no período atual · {report.coverage.previousDays}/{period} no anterior.</p>{!report.dataQuality.comparable && <p className="mt-1 text-[9px] font-medium text-amber-300 print:text-gray-700">O período anterior não possui base suficiente; “Novo no período” substitui um percentual artificial.</p>}</section>

      {report.symptoms.length > 0 && <section className="rounded-[24px] border border-surface-border bg-surface p-4 print:border-gray-300 print:bg-white"><SectionTitle icon={HeartPulse} title="Sintomas registrados"/><div className="mt-3 divide-y divide-surface-border/50">{report.symptoms.map((item) => <div key={item.label} className="flex items-center justify-between gap-3 py-2.5"><div><p className="text-sm font-semibold text-ink-primary print:text-black">{item.label}</p><p className="text-[10px] text-ink-muted print:text-gray-600">{item.occurrences} ocorrência(s) em {item.days} dia(s)</p></div><span className="font-mono text-xs text-violet-300 print:text-black">{item.averageIntensity === null ? "Sem escala" : `Média ${item.averageIntensity}/10`}</span></div>)}</div></section>}

      {report.medications.length > 0 && <section className="rounded-[24px] border border-surface-border bg-surface p-4 print:border-gray-300 print:bg-white"><SectionTitle icon={Pill} title="Doses registradas por medicamento"/><div className="mt-3 divide-y divide-surface-border/50">{report.medications.map((item) => <div key={item.id} className="py-2.5"><div className="flex justify-between gap-3"><p className="text-sm font-semibold text-ink-primary print:text-black">{item.name} <span className="font-normal text-ink-muted">{item.dosage}</span></p><span className="font-mono text-[10px] text-ink-faint print:text-gray-600">{item.scheduledTaken + item.sosTaken + item.extraTaken} tomadas</span></div><p className="mt-1 text-[10px] text-ink-muted print:text-gray-600">Programadas {item.scheduledTaken} · SOS {item.sosTaken} · Extras {item.extraTaken} · Ignoradas {item.ignored}</p></div>)}</div></section>}

      {report.insights.length > 0 && <section className="rounded-[24px] border border-violet-400/20 bg-violet-400/[0.04] p-4 print:border-gray-300 print:bg-white"><SectionTitle icon={Activity} title="Padrões percebidos"/><p className="mt-1 text-[10px] text-ink-muted print:text-gray-600">Somente padrões compatíveis com esta janela e com confiança média ou alta. Associação temporal não significa causalidade.</p><div className="mt-3 space-y-2">{report.insights.map((insight) => <div key={insight.id} className="rounded-2xl border border-violet-400/15 bg-surface-raised p-3 print:border-gray-300 print:bg-white"><div className="flex items-center justify-between gap-2"><p className="text-xs font-semibold text-ink-primary print:text-black">{insight.titulo}</p><span className="shrink-0 font-mono text-[8px] uppercase text-violet-300 print:text-gray-700">{insight.confianca}{insight.periodoDias ? ` · ${insight.periodoDias}d` : ""}</span></div><p className="mt-1 text-[10px] leading-relaxed text-ink-muted print:text-gray-600">{insight.mensagem}</p>{insight.acaoSegura && <p className="mt-2 text-[10px] font-medium text-emerald-300 print:text-black">Próximo passo: {insight.acaoSegura}</p>}</div>)}</div></section>}

      {(report.dataQuality.discardedRecords > 0 || report.dataQuality.inconsistencies.length > 0) && <section className="rounded-[24px] border border-amber-400/20 bg-amber-400/[0.05] p-4 print:border-gray-300 print:bg-white"><SectionTitle icon={Info} title="Qualidade dos dados"/><p className="mt-1 text-[10px] text-ink-muted print:text-gray-600">O relatório separa ausência de dados de valor zero e sinaliza informações que não puderam entrar na leitura.</p>{report.dataQuality.discardedRecords > 0 && <p className="mt-2 text-[10px] font-medium text-amber-300 print:text-gray-700">{report.dataQuality.discardedRecords} registro(s) com data inválida foram desconsiderados.</p>}<ul className="mt-2 space-y-1">{report.dataQuality.inconsistencies.map((message) => <li key={message} className="text-[9px] leading-relaxed text-ink-muted print:text-gray-600">• {message}</li>)}</ul></section>}

      <div className="rounded-2xl border border-amber-400/20 bg-amber-400/[0.06] p-3 print:border-gray-300 print:bg-white"><Info size={14} className="mr-2 inline text-amber-300 print:text-black"/><span className="text-[10px] leading-relaxed text-ink-muted print:text-gray-700">Este relatório organiza dados registrados no Vault. Não diagnostica, não prescreve e não recomenda alteração de medicamento ou dose.</span></div>
      <button type="button" onClick={() => window.print()} className="flex w-full items-center justify-center gap-2 rounded-2xl bg-emerald-300 py-3 font-semibold text-void print:hidden"><Printer size={17}/>Imprimir ou salvar em PDF</button>
    </section>
  </main></PageTransition>;
}

function SectionTitle({ icon: Icon, title }: { icon: typeof Activity; title: string }) { return <div className="flex items-center gap-2"><Icon size={15} className="text-emerald-300 print:text-black"/><h2 className="text-sm font-semibold text-ink-primary print:text-black">{title}</h2></div>; }
function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded-xl border border-surface-border/50 bg-surface-raised p-2.5 print:border-gray-300 print:bg-white"><p className="font-mono text-lg font-bold text-ink-primary print:text-black">{value}</p><p className="text-[8px] font-bold uppercase tracking-wide text-ink-muted print:text-gray-600">{label}</p></div>; }
function Comparison({ label, value }: { label: string; value: number | null }) { const tone = value === null || value > 0 ? "text-amber-300" : value < 0 ? "text-emerald-300" : "text-ink-muted"; return <div className="rounded-xl border border-surface-border/50 bg-surface-raised p-2.5 text-center print:border-gray-300 print:bg-white"><p className={`font-mono text-sm font-bold ${tone} print:text-black`}>{deltaLabel(value)}</p><p className="mt-0.5 text-[8px] uppercase text-ink-muted print:text-gray-600">{label}</p></div>; }
