"use client";
import { useEffect,useMemo,useState } from "react";
import { useRouter } from "next/navigation";
import { AlertTriangle,BrainCircuit,ChevronLeft,ChevronRight,CircleCheck,Database,Filter,Pill,Search,ShieldAlert,Sparkles,TrendingUp,X } from "lucide-react";
import { PageTransition } from "@/components/PageTransition";
import { useBrainV5Alerts } from "@/hooks/useBrainV5Alerts";
import type { BrainV5Alert,BrainV5Family,BrainV5Feedback,BrainV5State } from "@/lib/health-intelligence/brain-v5";
const meta:Record<BrainV5Family,{label:string;icon:typeof BrainCircuit}>={now:{label:"Agora",icon:AlertTriangle},medication:{label:"Medicamentos",icon:Pill},interaction:{label:"Interações e segurança",icon:ShieldAlert},pattern:{label:"Padrões",icon:TrendingUp},data_quality:{label:"Qualidade dos dados",icon:Database},other:{label:"Outros",icon:Sparkles}};
const fb:Array<[BrainV5Feedback,string]>=[["useful","Útil"],["already_knew","Já sabia"],["not_relevant","Não relevante"],["review_later","Revisar depois"],["dismissed","Dispensar"]];
const stateLabel:Record<BrainV5State,string>={active:"Ativo",acknowledged:"Visto",monitoring:"Acompanhando",resolved:"Resolvido"};
const ageDays=(iso:string)=>Math.max(0,(Date.now()-new Date(iso).getTime())/86400000);
export default function BrainV5Central(){
 const router=useRouter(),brain=useBrainV5Alerts();
 const [q,setQ]=useState(""),[family,setFamily]=useState<BrainV5Family|"all">("all"),[state,setState]=useState<BrainV5State|"open"|"all">("open"),[severity,setSeverity]=useState<"all"|"attention">("all"),[period,setPeriod]=useState<"all"|"7"|"30">("all"),[selectedKey,setSelectedKey]=useState<string|null>(null),[filtersOpen,setFiltersOpen]=useState(false);
 const selected=useMemo(()=>brain.records.find(x=>x.key===selectedKey)??null,[brain.records,selectedKey]);
 useEffect(()=>{if(typeof window==="undefined"||brain.isLoading)return;const id=new URLSearchParams(window.location.search).get("insight");if(!id)return;const hit=brain.records.find(x=>x.insight_id===id);if(hit){setSelectedKey(hit.key);void brain.seen(hit.key);}},[brain.isLoading,brain.records,brain.seen]);
 const list=useMemo(()=>brain.ranked.filter(x=>{if(state==="open"&&x.state==="resolved")return false;if(state!=="all"&&state!=="open"&&x.state!==state)return false;if(family!=="all"&&x.family!==family)return false;if(severity==="attention"&&x.severity_rank<400)return false;if(period!=="all"&&ageDays(x.last_detected_at)>Number(period))return false;const s=q.trim().toLowerCase();return !s||[x.snapshot.titulo,x.snapshot.mensagem,x.snapshot.categoria,...x.snapshot.evidencias,...x.snapshot.fontes_internas].join(" ").toLowerCase().includes(s);}),[brain.ranked,q,family,state,severity,period]);
 const open=(x:BrainV5Alert)=>{setSelectedKey(x.key);void brain.seen(x.key);};
 const activeFilterCount=(family!=="all"?1:0)+(state!=="open"?1:0)+(severity!=="all"?1:0)+(period!=="all"?1:0);
 const clearFilters=()=>{setFamily("all");setState("open");setSeverity("all");setPeriod("all");};
 const severityTone=(x:BrainV5Alert)=>x.severity_rank>=700?"border-coral/35 bg-coral/[0.055]":x.severity_rank>=400?"border-amber-400/25 bg-amber-400/[0.045]":"border-surface-border bg-surface";
 const iconTone=(x:BrainV5Alert)=>x.severity_rank>=700?"bg-coral/10 text-coral":x.severity_rank>=400?"bg-amber-400/10 text-amber-300":"bg-violet-400/10 text-violet-300";
 return <PageTransition><main className="min-h-screen bg-void px-4 pb-32 pt-5 header-safe-top text-ink-primary">
  <header className="mx-auto flex max-w-2xl items-start gap-3"><button onClick={()=>router.replace("/inteligencia")} className="rounded-2xl border border-surface-border bg-surface p-3"><ChevronLeft size={20}/></button><div><p className="font-mono text-[9px] uppercase tracking-[.25em] text-violet-300">VAULT INTELLIGENCE</p><h1 className="text-2xl font-bold">Central de Inteligência</h1><p className="mt-1 text-xs text-ink-muted">Sinais priorizados, evidências e histórico em um só lugar.</p></div></header>
  <section className="mx-auto mt-4 grid max-w-2xl grid-cols-4 gap-2">{[["Ativos",brain.counters.active],["Novos",brain.counters.new],["Atenção",brain.counters.attention],["Histórico",brain.counters.resolved]].map(([l,v])=><div key={String(l)} className="rounded-2xl border border-surface-border bg-surface p-3 text-center"><strong className="text-lg">{v}</strong><p className="text-[8px] uppercase text-ink-faint">{l}</p></div>)}</section>
  {/* VAULT_INTELLIGENCE_EXPERIENCE_V97_R1 */}
  <section className="mx-auto mt-4 max-w-2xl space-y-2">
   <div className="flex items-center gap-2">
    <div className="flex min-w-0 flex-1 items-center gap-2 rounded-2xl border border-surface-border bg-surface px-3"><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Pesquisar insight, medicamento ou evidência" className="min-w-0 flex-1 bg-transparent py-3 text-sm outline-none"/>{q&&<button onClick={()=>setQ("")}><X size={14}/></button>}</div>
    <button onClick={()=>setFiltersOpen(true)} className={"relative flex h-[46px] shrink-0 items-center gap-2 rounded-2xl border px-3 text-xs font-bold "+(activeFilterCount?"border-violet-400/40 bg-violet-400/10 text-violet-300":"border-surface-border bg-surface text-ink-muted")}><Filter size={16}/>Filtros{activeFilterCount>0&&<span className="flex h-5 min-w-5 items-center justify-center rounded-full bg-violet-400 px-1.5 text-[9px] font-black text-void">{activeFilterCount}</span>}</button>
   </div>
   <div className="flex items-center justify-between px-1"><p className="text-[10px] text-ink-faint">{list.length} insight{list.length===1?"":"s"} nesta visão</p>{activeFilterCount>0&&<button onClick={clearFilters} className="text-[10px] font-semibold text-violet-300">Limpar filtros</button>}</div>
  </section>
  {filtersOpen&&<div className="fixed inset-0 z-[95] flex items-end bg-black/65" onClick={()=>setFiltersOpen(false)}><div className="w-full rounded-t-[28px] border border-surface-border bg-surface p-5 pb-[calc(20px+env(safe-area-inset-bottom))]" onClick={e=>e.stopPropagation()}>
   <div className="flex items-center justify-between"><div><p className="text-[9px] font-bold uppercase tracking-[.2em] text-violet-300">Refinar Central</p><h2 className="mt-1 text-lg font-bold">Filtros</h2></div><button onClick={()=>setFiltersOpen(false)} className="rounded-xl border border-surface-border p-2"><X size={18}/></button></div>
   <div className="mt-4 space-y-4">
    <div><p className="mb-2 text-[10px] font-bold uppercase text-ink-faint">Área</p><div className="flex flex-wrap gap-2">{(["all",...Object.keys(meta)] as Array<"all"|BrainV5Family>).map(k=><button key={k} onClick={()=>setFamily(k)} className={"rounded-full border px-3 py-2 text-[10px] "+(family===k?"border-violet-400/40 bg-violet-400/10 text-violet-300":"border-surface-border text-ink-muted")}>{k==="all"?"Todas":meta[k].label}</button>)}</div></div>
    <div><p className="mb-2 text-[10px] font-bold uppercase text-ink-faint">Estado</p><div className="flex flex-wrap gap-2"><button onClick={()=>setState("open")} className={"rounded-full border px-3 py-2 text-[10px] "+(state==="open"?"border-violet-400/40 bg-violet-400/10 text-violet-300":"border-surface-border text-ink-muted")}>Em aberto</button><button onClick={()=>setState("all")} className={"rounded-full border px-3 py-2 text-[10px] "+(state==="all"?"border-violet-400/40 bg-violet-400/10 text-violet-300":"border-surface-border text-ink-muted")}>Todos</button><button onClick={()=>setState("monitoring")} className={"rounded-full border px-3 py-2 text-[10px] "+(state==="monitoring"?"border-violet-400/40 bg-violet-400/10 text-violet-300":"border-surface-border text-ink-muted")}>Acompanhando</button><button onClick={()=>setState("resolved")} className={"rounded-full border px-3 py-2 text-[10px] "+(state==="resolved"?"border-violet-400/40 bg-violet-400/10 text-violet-300":"border-surface-border text-ink-muted")}>Resolvidos</button></div></div>
    <div><p className="mb-2 text-[10px] font-bold uppercase text-ink-faint">Prioridade</p><div className="flex gap-2"><button onClick={()=>setSeverity("all")} className={"rounded-full border px-3 py-2 text-[10px] "+(severity==="all"?"border-violet-400/40 bg-violet-400/10 text-violet-300":"border-surface-border text-ink-muted")}>Todas</button><button onClick={()=>setSeverity("attention")} className={"rounded-full border px-3 py-2 text-[10px] "+(severity==="attention"?"border-amber-400/40 bg-amber-400/10 text-amber-300":"border-surface-border text-ink-muted")}>Requer atenção</button></div></div>
    <div><p className="mb-2 text-[10px] font-bold uppercase text-ink-faint">Período</p><div className="flex gap-2">{(["all","7","30"] as const).map(v=><button key={v} onClick={()=>setPeriod(v)} className={"rounded-full border px-3 py-2 text-[10px] "+(period===v?"border-violet-400/40 bg-violet-400/10 text-violet-300":"border-surface-border text-ink-muted")}>{v==="all"?"Todo período":v+" dias"}</button>)}</div></div>
   </div>
   <div className="mt-5 grid grid-cols-2 gap-2"><button onClick={clearFilters} className="rounded-2xl border border-surface-border p-3 text-sm text-ink-muted">Limpar</button><button onClick={()=>setFiltersOpen(false)} className="rounded-2xl bg-violet-400 p-3 text-sm font-bold text-void">Ver {list.length}</button></div>
  </div></div>}
  <section className="mx-auto mt-4 max-w-2xl space-y-2.5">{brain.isLoading?<div className="rounded-2xl border border-surface-border bg-surface p-5 text-sm text-ink-muted">Organizando o histórico…</div>:!list.length?<div className="rounded-2xl border border-emerald-400/15 bg-emerald-400/5 p-5 text-sm text-emerald-300"><CircleCheck size={17} className="mr-2 inline"/>Nada nesta visão.</div>:list.map(x=>{const I=meta[x.family].icon;return <button key={x.key} onClick={()=>open(x)} className={"flex w-full items-center gap-3 rounded-[22px] border p-4 text-left "+severityTone(x)}><div className={"rounded-2xl p-3 "+iconTone(x)}><I size={18}/></div><div className="min-w-0 flex-1"><div className="flex gap-2"><p className="truncate text-sm font-bold">{x.snapshot.titulo}</p>{!x.last_seen_at&&<span className="text-[8px] text-ice">NOVO</span>}</div><p className="mt-1 line-clamp-2 text-xs text-ink-muted">{x.snapshot.mensagem}</p><p className="mt-2 font-mono text-[8px] uppercase text-ink-faint">{meta[x.family].label} · {stateLabel[x.state]} · {x.occurrences} ocorrência(s)</p></div><ChevronRight size={16}/></button>})}</section>
  {selected&&<div className="fixed inset-0 z-[90] flex items-end bg-black/65" onClick={()=>setSelectedKey(null)}><div className="max-h-[88dvh] w-full overflow-y-auto rounded-t-[28px] border border-surface-border bg-surface p-5" onClick={e=>e.stopPropagation()}><div className="flex gap-3"><div className="flex-1"><p className="text-[9px] uppercase text-violet-300">{meta[selected.family].label} · {stateLabel[selected.state]}</p><h2 className="text-xl font-bold">{selected.snapshot.titulo}</h2></div><button onClick={()=>setSelectedKey(null)}><X/></button></div><p className="mt-3 text-sm text-ink-muted">{selected.snapshot.mensagem}</p><div className="mt-4 rounded-2xl border border-surface-border bg-black/10 p-4"><h3 className="text-sm font-bold">Por que o Vault mostrou isso?</h3><div className="mt-2 space-y-1">{selected.snapshot.evidencias.length?selected.snapshot.evidencias.map(e=><p key={e} className="text-xs text-ink-muted">• {e}</p>):<p className="text-xs text-ink-muted">Esta regra não forneceu evidências textuais adicionais.</p>}</div><p className="mt-3 text-[10px] text-ink-faint">Confiança {selected.snapshot.confianca} · amostra {selected.snapshot.amostra} · ocorrência {selected.occurrences} · episódio {selected.episode||1}{selected.snapshot.periodo_dias?` · janela ${selected.snapshot.periodo_dias}d`:""}</p>{selected.snapshot.acao_segura&&<p className="mt-3 text-xs text-ice">{selected.snapshot.acao_segura}</p>}{selected.snapshot.limitacao_seguranca&&<p className="mt-2 text-[10px] text-amber-300">{selected.snapshot.limitacao_seguranca}</p>}</div>{selected.snapshot.fontes_externas.length>0&&<div className="mt-3 rounded-2xl border border-surface-border p-4"><p className="text-xs font-bold">Fontes regulatórias revisadas</p>{selected.snapshot.fontes_externas.map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer" className="mt-2 block text-xs text-ice underline">{s.autoridade} · {s.titulo}</a>)}</div>}<div className="mt-4 flex flex-wrap gap-2">{fb.map(([v,l])=><button key={v} onClick={()=>void brain.feedback(selected.key,v)} className={`rounded-full border px-3 py-2 text-[10px] ${selected.feedback===v?"border-violet-400/40 bg-violet-400/10 text-violet-300":"border-surface-border"}`}>{l}</button>)}</div><div className="mt-4 grid grid-cols-2 gap-2">{selected.snapshot.link?<button onClick={()=>router.push(selected.snapshot.link!)} className="rounded-2xl bg-ice p-3 text-sm font-bold text-void">Abrir contexto</button>:<div/>}<button onClick={()=>void brain.state(selected.key,selected.state==="resolved"?"active":"resolved")} className="rounded-2xl border border-surface-border p-3 text-sm">{selected.state==="resolved"?"Reabrir":"Marcar resolvido"}</button></div></div></div>}
 </main></PageTransition>;
}
