"use client";
import { useMemo, useState } from "react";
import { ArrowLeft, Bell, Droplets } from "lucide-react";
import { useRouter } from "next/navigation";
import { useRegistrosSaude } from "@/hooks/useRegistrosSaude";
import { useActivePersonId } from "@/hooks/useActivePersonId";
const key=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
export default function HydrationPage(){ const router=useRouter(); const {activePersonId}=useActivePersonId(); const {registros,createRegistro}=useRegistrosSaude(); const storageKey=`vault:hydration-goal:${activePersonId||"none"}`; const [goal,setGoal]=useState(()=>typeof window!=="undefined"?Number(localStorage.getItem(storageKey)||2000):2000); const [custom,setCustom]=useState("350"); const [busy,setBusy]=useState(false); const today=key(new Date()); const water=useMemo(()=>registros.filter(r=>r.tipo==="agua"&&r.data===today&&r.unidade_medida==="ml"&&typeof r.valor_numerico==="number"),[registros,today]); const total=water.reduce((s,r)=>s+(r.valor_numerico||0),0); const days=useMemo(()=>{const m=new Map<string,number>(); registros.filter(r=>r.tipo==="agua"&&r.unidade_medida==="ml"&&typeof r.valor_numerico==="number").forEach(r=>m.set(r.data,(m.get(r.data)||0)+(r.valor_numerico||0))); return [...m.entries()].sort((a,b)=>b[0].localeCompare(a[0])).slice(0,7)},[registros]); const avg=days.length?Math.round(days.reduce((s,x)=>s+x[1],0)/days.length):null;
 async function add(ml:number){if(!Number.isFinite(ml)||ml<=0)return;setBusy(true);try{const n=new Date();await createRegistro({categoria:"habito",tipo:"agua",nome:"Água",valor_medicao:`${ml} ml`,valor_numerico:ml,unidade_medida:"ml",registro_chave:"habito:agua",data:key(n),horario:`${String(n.getHours()).padStart(2,"0")}:${String(n.getMinutes()).padStart(2,"0")}`});}finally{setBusy(false)}}
 function saveGoal(v:number){const safe=Math.max(1,Math.round(v));setGoal(safe);localStorage.setItem(storageKey,String(safe));}
 return <main className="min-h-screen bg-void px-4 pb-28 pt-6 text-ink-primary"><header className="mx-auto flex max-w-xl items-center gap-3"><button onClick={()=>router.replace("/saude/registros")} className="rounded-xl border border-surface-border p-2"><ArrowLeft size={20}/></button><div className="flex-1"><h1 className="font-display text-2xl font-bold">Hidratação</h1><p className="text-sm text-ink-muted">Registros reais em ml</p></div><button onClick={()=>router.push("/saude/lembretes")} className="rounded-xl border border-surface-border p-2"><Bell size={20}/></button></header><section className="mx-auto mt-6 max-w-xl rounded-3xl border border-ice/20 bg-surface p-5"><div className="flex items-center gap-3"><Droplets className="text-ice"/><div><p className="text-3xl font-bold">{total} ml</p><p className="text-sm text-ink-muted">registrados hoje · meta manual {goal} ml</p></div></div><div className="mt-4 h-3 overflow-hidden rounded-full bg-void"><div className="h-full rounded-full bg-ice transition-all" style={{width:`${Math.min(100,(total/goal)*100)}%`}}/></div><div className="mt-4 flex gap-2"><button disabled={busy} onClick={()=>add(250)} className="flex-1 rounded-xl bg-ice/10 p-3 text-ice">+250 ml</button><button disabled={busy} onClick={()=>add(500)} className="flex-1 rounded-xl bg-ice/10 p-3 text-ice">+500 ml</button></div><div className="mt-3 flex gap-2"><input inputMode="numeric" value={custom} onChange={e=>setCustom(e.target.value)} className="min-w-0 flex-1 rounded-xl border border-surface-border bg-void p-3"/><button onClick={()=>add(Number(custom))} className="rounded-xl border border-ice/40 px-4">Registrar</button></div><label className="mt-5 block text-xs text-ink-muted">Meta diária manual (ml)</label><input type="number" min="1" value={goal} onChange={e=>saveGoal(Number(e.target.value))} className="mt-1 w-full rounded-xl border border-surface-border bg-void p-3"/></section><section className="mx-auto mt-4 max-w-xl rounded-3xl border border-surface-border bg-surface p-5"><h2 className="font-semibold">Histórico observado</h2><p className="mt-1 text-sm text-ink-muted">{avg===null?"Ainda não há dias registrados para calcular média.":`Média dos ${days.length} dias com registros: ${avg} ml.`}</p><div className="mt-3 grid gap-2">{days.map(([d,v])=><div key={d} className="flex justify-between rounded-xl bg-void p-3"><span>{d}</span><strong>{v} ml</strong></div>)}</div><p className="mt-3 text-xs text-ink-muted">Dias sem registro não são tratados como consumo zero. Esta visão é descritiva e não substitui orientação profissional.</p></section></main>}
