begin;
alter table public.fornecimentos drop constraint fornecimentos_origem_check;
alter table public.fornecimentos add constraint fornecimentos_origem_check check(origem in ('comprado','municipal','estadual_ceaf','farmacia_popular','outro'));
alter table public.fornecimentos add column if not exists uf text check(uf is null or uf ~ '^[A-Z]{2}$');
alter table public.fornecimentos add column if not exists indicacao text;
alter table public.fornecimentos add column if not exists catalogo_versao text;
alter table public.fornecimento_ciclos add column if not exists uf_snapshot text;
alter table public.fornecimento_ciclos add column if not exists indicacao_snapshot text;
alter table public.fornecimento_ciclos add column if not exists origem_snapshot text;
alter table public.fornecimento_ciclos add column if not exists motivo text check(motivo is null or motivo in ('inicial','renovacao','troca','inclusao','ajuste_dose','retomada','outro'));
alter table public.fornecimento_ciclos add column if not exists preparar_ate date;
alter table public.fornecimento_ciclos add column if not exists consulta_id uuid;
alter table public.fornecimento_ciclos add column if not exists documentos_pessoais_conferidos boolean not null default false;
alter table public.fornecimento_ciclos add column if not exists exigencia_local text;
alter table public.fornecimento_ciclos add column if not exists regra_versao text;
alter table public.fornecimento_itens add column if not exists catalogo_id text;
create unique index if not exists consultas_supply_scope on public.consultas(id,user_id,person_id);
alter table public.fornecimento_ciclos add constraint fornecimento_consulta_scope foreign key(consulta_id,user_id,person_id) references public.consultas(id,user_id,person_id) on delete set null (consulta_id);
create index if not exists fornecimento_consulta_idx on public.fornecimento_ciclos(consulta_id);
commit;
