"use client";
import { useState } from "react";
import { ArrowLeft, Bell, Pause, Play, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { useHealthReminders } from "@/hooks/useHealthReminders";
export default function HealthRemindersPage() {
  const router = useRouter(); const { reminders, createReminder, pauseReminder, deleteReminder } = useHealthReminders(); const [title,setTitle]=useState("Registrar hidratação"); const [time,setTime]=useState("10:00"); const [busy,setBusy]=useState(false);
  async function add(){ setBusy(true); try { await createReminder({ title, body:"Registre o que você bebeu — sem presumir consumo.", target_type:"health_record:agua", target_route:"/saude/hidratacao", time, frequency:"daily", weekdays:[], status:"active" }); } finally { setBusy(false); } }
  return <main className="min-h-screen bg-void px-4 pb-28 pt-6 text-ink-primary"><header className="mx-auto flex max-w-xl items-center gap-3"><button onClick={()=>router.replace("/saude/registros")} className="rounded-xl border border-surface-border p-2"><ArrowLeft size={20}/></button><div><h1 className="font-display text-2xl font-bold">Lembretes de saúde</h1><p className="text-sm text-ink-muted">As regras sincronizam; cada aparelho agenda localmente.</p></div></header><section className="mx-auto mt-6 max-w-xl rounded-3xl border border-surface-border bg-surface p-4"><div className="grid gap-3"><input value={title} onChange={e=>setTitle(e.target.value)} className="rounded-xl border border-surface-border bg-void p-3" aria-label="Título"/><input type="time" value={time} onChange={e=>setTime(e.target.value)} className="rounded-xl border border-surface-border bg-void p-3"/><button disabled={busy} onClick={add} className="rounded-xl bg-ice p-3 font-semibold text-void">{busy?"Salvando…":"Criar lembrete diário"}</button></div><p className="mt-3 text-xs text-ink-muted">No app instalado, o Vault usa notificação nativa. No navegador/PWA, o sistema não garante alarmes recorrentes quando o app está fechado.</p></section><section className="mx-auto mt-4 grid max-w-xl gap-3">{reminders.map(r=><article key={r.id} className="flex items-center gap-3 rounded-2xl border border-surface-border bg-surface p-4"><Bell size={18} className="text-ice"/><div className="min-w-0 flex-1"><p className="truncate font-semibold">{r.title}</p><p className="text-sm text-ink-muted">{r.time} · {r.status === "paused"?"pausado":"ativo"}</p></div><button aria-label={r.status==="paused"?"Ativar":"Pausar"} onClick={()=>pauseReminder(r.id,r.status!=="paused")} className="p-2">{r.status==="paused"?<Play size={18}/>:<Pause size={18}/>}</button><button aria-label="Excluir" onClick={()=>deleteReminder(r.id)} className="p-2 text-coral"><Trash2 size={18}/></button></article>)}</section></main>;
}
